name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Deploy to Raspberry Pi
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --delete
          path: |
            dist/
            node_modules/
            recipes.json
            package.json
          remote_path: /opt/recipes/
          remote_host: $${{ secrets.DEPLOY_HOST }}
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Restart application
        uses: appleboy/ssh-action@v1
        with:
          host: webhost.cerbrus.nl
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: sudo systemctl restart recipes